import dayjs from 'dayjs/esm';

import { IContrat, NewContrat } from './contrat.model';

export const sampleWithRequiredData: IContrat = {
  id: 16857,
  numeroContratCollectif: 'supposing pepper',
  migre: 'utterly shameless fantastic',
  codeEntiteRattachement: 'snack lovingly amongst',
  codeCentreGestion: 'profitable obsess',
  codeGroupeGestion: 'phooey mount royal',
  codeReseauDistribution: 'tarry',
  typeContratCollectif: 'athwart sniff',
  etatContrat: 'er anguished',
  dateEffetPremiereSouscription: dayjs('2025-08-21'),
  codeNatureCouverture: 'readily',
  codeOffre: 'suspiciously about near',
  numeroVersionOffre: 'self-confidence screw triumphantly',
  echeancePrincipale: 'but psst',
  codeOrganismePorteurRisque: 'monthly infamous',
  indicateurPorteurRisque: 'emerge',
  codeOrganismeProducteurFicheDsn: 'sanity plait forsaken',
  codeOrganismeDelegataireCotisations: 'nor',
  codeOrganismeDelegatairePrestations: 'snarling badly',
  datePremierMoisCotisationAutorise: 'unnecessarily fatal',
  numeroOperationNiveau0: 8160,
  statut: 'frantically snarling gradient',
};

export const sampleWithPartialData: IContrat = {
  id: 21890,
  numeroContratCollectif: 'filthy ouch doorpost',
  migre: 'resort',
  codeEntiteRattachement: 'taut windy',
  codeCentreGestion: 'gadzooks frugal',
  codeGroupeGestion: 'through until yellow',
  codeReseauDistribution: 'midst down besides',
  typeContratCollectif: 'duh deafening despite',
  etatContrat: 'resource',
  dateEffetPremiereSouscription: dayjs('2025-08-21'),
  dateEffetDerniereResiliation: dayjs('2025-08-22'),
  codeNatureCouverture: 'than pulp',
  codeOffre: 'cross over',
  numeroVersionOffre: 'oh soggy',
  echeancePrincipale: 'uselessly cope yum',
  codeOrganismePorteurRisque: 'bitterly',
  indicateurPorteurRisque: 'duh yahoo carelessly',
  codeOrganismeProducteurFicheDsn: 'supposing mysteriously roger',
  codeOrganismeDelegataireCotisations: 'rosemary',
  codeOrganismeDelegatairePrestations: 'hydrolyze below willow',
  datePremierMoisCotisationAutorise: 'alongside',
  numeroOperationNiveau0: 19742,
  statut: 'upset',
};

export const sampleWithFullData: IContrat = {
  id: 4932,
  numeroContratCollectif: 'undergo fooey',
  migre: 'incidentally given healthily',
  codeEntiteRattachement: 'milestone hungrily',
  codeCentreGestion: 'border cleaner',
  codeGroupeGestion: 'ack restfully',
  codeReseauDistribution: 'gadzooks supposing delightfully',
  typeContratCollectif: 'instead blah lively',
  etatContrat: 'near whether',
  dateEffetPremiereSouscription: dayjs('2025-08-22'),
  dateEffetDerniereResiliation: dayjs('2025-08-22'),
  motifResiliation: 'wherever fortunate',
  codeNatureCouverture: 'whoa rosy badly',
  codeOffre: 'funny',
  numeroVersionOffre: 'forenenst assured',
  echeancePrincipale: 'immediately qualified pleasant',
  codeOrganismePorteurRisque: 'boldly',
  indicateurPorteurRisque: 'consequently',
  codeOrganismeProducteurFicheDsn: 'why thankfully',
  codeOrganismeDelegataireCotisations: 'ugh bliss specific',
  codeOrganismeDelegatairePrestations: 'dim elegantly whoever',
  datePremierMoisCotisationAutorise: 'obesity considering shrilly',
  numeroOperationNiveau0: 14138,
  statut: 'conceptualize turret zowie',
};

export const sampleWithNewData: NewContrat = {
  numeroContratCollectif: 'concentration um',
  migre: 'miserly',
  codeEntiteRattachement: 'yum',
  codeCentreGestion: 'near kit',
  codeGroupeGestion: 'talkative hence',
  codeReseauDistribution: 'radiant jive as',
  typeContratCollectif: 'if limply badly',
  etatContrat: 'oof galvanize',
  dateEffetPremiereSouscription: dayjs('2025-08-22'),
  codeNatureCouverture: 'regarding',
  codeOffre: 'overcoat avalanche brisk',
  numeroVersionOffre: 'calmly strait velvety',
  echeancePrincipale: 'ack',
  codeOrganismePorteurRisque: 'function instead sermon',
  indicateurPorteurRisque: 'off exonerate reword',
  codeOrganismeProducteurFicheDsn: 'pish over',
  codeOrganismeDelegataireCotisations: 'zowie quietly even',
  codeOrganismeDelegatairePrestations: 'where',
  datePremierMoisCotisationAutorise: 'rationale phooey profitable',
  numeroOperationNiveau0: 21922,
  statut: 'neglect',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
