package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DemandeXRMAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeXRMAllPropertiesEquals(DemandeXRM expected, DemandeXRM actual) {
        assertDemandeXRMAutoGeneratedPropertiesEquals(expected, actual);
        assertDemandeXRMAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeXRMAllUpdatablePropertiesEquals(DemandeXRM expected, DemandeXRM actual) {
        assertDemandeXRMUpdatableFieldsEquals(expected, actual);
        assertDemandeXRMUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeXRMAutoGeneratedPropertiesEquals(DemandeXRM expected, DemandeXRM actual) {
        assertThat(actual)
            .as("Verify DemandeXRM auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeXRMUpdatableFieldsEquals(DemandeXRM expected, DemandeXRM actual) {
        assertThat(actual)
            .as("Verify DemandeXRM relevant properties")
            .satisfies(a -> assertThat(a.getDateDemande()).as("check dateDemande").isEqualTo(expected.getDateDemande()))
            .satisfies(a -> assertThat(a.getDateEnvoiAI()).as("check dateEnvoiAI").isEqualTo(expected.getDateEnvoiAI()))
            .satisfies(a -> assertThat(a.getDateEnvoiIVS()).as("check dateEnvoiIVS").isEqualTo(expected.getDateEnvoiIVS()))
            .satisfies(a -> assertThat(a.getaI()).as("check aI").isEqualTo(expected.getaI()))
            .satisfies(a -> assertThat(a.getiVS()).as("check iVS").isEqualTo(expected.getiVS()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeXRMUpdatableRelationshipsEquals(DemandeXRM expected, DemandeXRM actual) {
        // empty method
    }
}
