package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GarantieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGarantieAllPropertiesEquals(Garantie expected, Garantie actual) {
        assertGarantieAutoGeneratedPropertiesEquals(expected, actual);
        assertGarantieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGarantieAllUpdatablePropertiesEquals(Garantie expected, Garantie actual) {
        assertGarantieUpdatableFieldsEquals(expected, actual);
        assertGarantieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGarantieAutoGeneratedPropertiesEquals(Garantie expected, Garantie actual) {
        assertThat(actual)
            .as("Verify Garantie auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGarantieUpdatableFieldsEquals(Garantie expected, Garantie actual) {
        assertThat(actual)
            .as("Verify Garantie relevant properties")
            .satisfies(a ->
                assertThat(a.getCodeGarantieTechnique()).as("check codeGarantieTechnique").isEqualTo(expected.getCodeGarantieTechnique())
            )
            .satisfies(a -> assertThat(a.getCodeEtatGarantie()).as("check codeEtatGarantie").isEqualTo(expected.getCodeEtatGarantie()))
            .satisfies(a ->
                assertThat(a.getDateAdhesionGarantie()).as("check dateAdhesionGarantie").isEqualTo(expected.getDateAdhesionGarantie())
            )
            .satisfies(a ->
                assertThat(a.getDateRadiationGarantie()).as("check dateRadiationGarantie").isEqualTo(expected.getDateRadiationGarantie())
            )
            .satisfies(a -> assertThat(a.getCodeAssureur()).as("check codeAssureur").isEqualTo(expected.getCodeAssureur()))
            .satisfies(a -> assertThat(a.getCodeFormule()).as("check codeFormule").isEqualTo(expected.getCodeFormule()))
            .satisfies(a -> assertThat(a.getCodePack()).as("check codePack").isEqualTo(expected.getCodePack()))
            .satisfies(a -> assertThat(a.getTypePack()).as("check typePack").isEqualTo(expected.getTypePack()))
            .satisfies(a -> assertThat(a.getTitrePack()).as("check titrePack").isEqualTo(expected.getTitrePack()))
            .satisfies(a -> assertThat(a.getCodeSousPack()).as("check codeSousPack").isEqualTo(expected.getCodeSousPack()))
            .satisfies(a -> assertThat(a.getTypeSousPack()).as("check typeSousPack").isEqualTo(expected.getTypeSousPack()))
            .satisfies(a -> assertThat(a.getTitreSousPack()).as("check titreSousPack").isEqualTo(expected.getTitreSousPack()))
            .satisfies(a ->
                assertThat(a.getCodeTypePrestations()).as("check codeTypePrestations").isEqualTo(expected.getCodeTypePrestations())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGarantieUpdatableRelationshipsEquals(Garantie expected, Garantie actual) {
        assertThat(actual)
            .as("Verify Garantie relationships")
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()));
    }
}
