package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TauxAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTauxAllPropertiesEquals(Taux expected, Taux actual) {
        assertTauxAutoGeneratedPropertiesEquals(expected, actual);
        assertTauxAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTauxAllUpdatablePropertiesEquals(Taux expected, Taux actual) {
        assertTauxUpdatableFieldsEquals(expected, actual);
        assertTauxUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTauxAutoGeneratedPropertiesEquals(Taux expected, Taux actual) {
        assertThat(actual)
            .as("Verify Taux auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTauxUpdatableFieldsEquals(Taux expected, Taux actual) {
        assertThat(actual)
            .as("Verify Taux relevant properties")
            .satisfies(a ->
                assertThat(a.getCodeVariableDeclarative())
                    .as("check codeVariableDeclarative")
                    .isEqualTo(expected.getCodeVariableDeclarative())
            )
            .satisfies(a ->
                assertThat(a.getUniteVariableDeclarative())
                    .as("check uniteVariableDeclarative")
                    .isEqualTo(expected.getUniteVariableDeclarative())
            )
            .satisfies(a ->
                assertThat(a.getValeurFacteurMontant()).as("check valeurFacteurMontant").isEqualTo(expected.getValeurFacteurMontant())
            )
            .satisfies(a -> assertThat(a.getValeurFacteurTaux()).as("check valeurFacteurTaux").isEqualTo(expected.getValeurFacteurTaux()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTauxUpdatableRelationshipsEquals(Taux expected, Taux actual) {
        assertThat(actual)
            .as("Verify Taux relationships")
            .satisfies(a -> assertThat(a.getGarantie()).as("check garantie").isEqualTo(expected.getGarantie()));
    }
}
